//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramKonstruktion.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SsnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Ssn {
            get {
                return this.SsnField;
            }
            set {
                if ((object.ReferenceEquals(this.SsnField, value) != true)) {
                    this.SsnField = value;
                    this.RaisePropertyChanged("Ssn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebServiceERP1Soap")]
    public interface WebServiceERP1Soap {
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        ProgramKonstruktion.ServiceReference1.CreateEmployeeResponse CreateEmployee(ProgramKonstruktion.ServiceReference1.CreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.ServiceReference1.CreateEmployeeResponse> CreateEmployeeAsync(ProgramKonstruktion.ServiceReference1.CreateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        ProgramKonstruktion.ServiceReference1.FindEmployeeResponse FindEmployee(ProgramKonstruktion.ServiceReference1.FindEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.ServiceReference1.FindEmployeeResponse> FindEmployeeAsync(ProgramKonstruktion.ServiceReference1.FindEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ServiceReference1.CreateEmployeeRequestBody Body;
        
        public CreateEmployeeRequest() {
        }
        
        public CreateEmployeeRequest(ProgramKonstruktion.ServiceReference1.CreateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ssn;
        
        public CreateEmployeeRequestBody() {
        }
        
        public CreateEmployeeRequestBody(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            this.no = no;
            this.FirstName = FirstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
            this.address = address;
            this.phoneNumber = phoneNumber;
            this.email = email;
            this.ssn = ssn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ServiceReference1.CreateEmployeeResponseBody Body;
        
        public CreateEmployeeResponse() {
        }
        
        public CreateEmployeeResponse(ProgramKonstruktion.ServiceReference1.CreateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProgramKonstruktion.ServiceReference1.Employee CreateEmployeeResult;
        
        public CreateEmployeeResponseBody() {
        }
        
        public CreateEmployeeResponseBody(ProgramKonstruktion.ServiceReference1.Employee CreateEmployeeResult) {
            this.CreateEmployeeResult = CreateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ServiceReference1.FindEmployeeRequestBody Body;
        
        public FindEmployeeRequest() {
        }
        
        public FindEmployeeRequest(ProgramKonstruktion.ServiceReference1.FindEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        public FindEmployeeRequestBody() {
        }
        
        public FindEmployeeRequestBody(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ServiceReference1.FindEmployeeResponseBody Body;
        
        public FindEmployeeResponse() {
        }
        
        public FindEmployeeResponse(ProgramKonstruktion.ServiceReference1.FindEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProgramKonstruktion.ServiceReference1.Employee FindEmployeeResult;
        
        public FindEmployeeResponseBody() {
        }
        
        public FindEmployeeResponseBody(ProgramKonstruktion.ServiceReference1.Employee FindEmployeeResult) {
            this.FindEmployeeResult = FindEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceERP1SoapChannel : ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceERP1SoapClient : System.ServiceModel.ClientBase<ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap>, ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap {
        
        public WebServiceERP1SoapClient() {
        }
        
        public WebServiceERP1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceERP1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceERP1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceERP1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramKonstruktion.ServiceReference1.CreateEmployeeResponse ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap.CreateEmployee(ProgramKonstruktion.ServiceReference1.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public ProgramKonstruktion.ServiceReference1.Employee CreateEmployee(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            ProgramKonstruktion.ServiceReference1.CreateEmployeeRequest inValue = new ProgramKonstruktion.ServiceReference1.CreateEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ServiceReference1.CreateEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.FirstName = FirstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            inValue.Body.ssn = ssn;
            ProgramKonstruktion.ServiceReference1.CreateEmployeeResponse retVal = ((ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap)(this)).CreateEmployee(inValue);
            return retVal.Body.CreateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramKonstruktion.ServiceReference1.CreateEmployeeResponse> ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap.CreateEmployeeAsync(ProgramKonstruktion.ServiceReference1.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.ServiceReference1.CreateEmployeeResponse> CreateEmployeeAsync(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            ProgramKonstruktion.ServiceReference1.CreateEmployeeRequest inValue = new ProgramKonstruktion.ServiceReference1.CreateEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ServiceReference1.CreateEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.FirstName = FirstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            inValue.Body.ssn = ssn;
            return ((ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap)(this)).CreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramKonstruktion.ServiceReference1.FindEmployeeResponse ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap.FindEmployee(ProgramKonstruktion.ServiceReference1.FindEmployeeRequest request) {
            return base.Channel.FindEmployee(request);
        }
        
        public ProgramKonstruktion.ServiceReference1.Employee FindEmployee(string no) {
            ProgramKonstruktion.ServiceReference1.FindEmployeeRequest inValue = new ProgramKonstruktion.ServiceReference1.FindEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ServiceReference1.FindEmployeeRequestBody();
            inValue.Body.no = no;
            ProgramKonstruktion.ServiceReference1.FindEmployeeResponse retVal = ((ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap)(this)).FindEmployee(inValue);
            return retVal.Body.FindEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramKonstruktion.ServiceReference1.FindEmployeeResponse> ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap.FindEmployeeAsync(ProgramKonstruktion.ServiceReference1.FindEmployeeRequest request) {
            return base.Channel.FindEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.ServiceReference1.FindEmployeeResponse> FindEmployeeAsync(string no) {
            ProgramKonstruktion.ServiceReference1.FindEmployeeRequest inValue = new ProgramKonstruktion.ServiceReference1.FindEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ServiceReference1.FindEmployeeRequestBody();
            inValue.Body.no = no;
            return ((ProgramKonstruktion.ServiceReference1.WebServiceERP1Soap)(this)).FindEmployeeAsync(inValue);
        }
    }
}
