//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProgramKonstruktion.NewWebRefMeta {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceERP12Soap", Namespace="http://grupp2.ics.lu.se/")]
    public partial class WebServiceERP12 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback CreateEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback DeleteEmployeeOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowContentOfCronusOperationCompleted;
        
        private System.Threading.SendOrPostCallback EmployeeAndRelativesOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowSickEmployees2004OperationCompleted;
        
        private System.Threading.SendOrPostCallback MostAbsentEmployeesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllKeysOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllIndexesOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllTableConstrainsOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllTablesInDatabaseSolOneOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllTablesInDatabaseSolTwoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllColEmpTableSolOneOperationCompleted;
        
        private System.Threading.SendOrPostCallback AllColEmpTableSolTwoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowFileOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebServiceERP12() {
            this.Url = global::ProgramKonstruktion.Properties.Settings.Default.ProgramKonstruktion_NewWebRefMeta_WebServiceERP12;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event CreateEmployeeCompletedEventHandler CreateEmployeeCompleted;
        
        /// <remarks/>
        public event FindEmployeeCompletedEventHandler FindEmployeeCompleted;
        
        /// <remarks/>
        public event UpdateEmployeeCompletedEventHandler UpdateEmployeeCompleted;
        
        /// <remarks/>
        public event DeleteEmployeeCompletedEventHandler DeleteEmployeeCompleted;
        
        /// <remarks/>
        public event ShowContentOfCronusCompletedEventHandler ShowContentOfCronusCompleted;
        
        /// <remarks/>
        public event EmployeeAndRelativesCompletedEventHandler EmployeeAndRelativesCompleted;
        
        /// <remarks/>
        public event ShowSickEmployees2004CompletedEventHandler ShowSickEmployees2004Completed;
        
        /// <remarks/>
        public event MostAbsentEmployeesCompletedEventHandler MostAbsentEmployeesCompleted;
        
        /// <remarks/>
        public event AllKeysCompletedEventHandler AllKeysCompleted;
        
        /// <remarks/>
        public event AllIndexesCompletedEventHandler AllIndexesCompleted;
        
        /// <remarks/>
        public event AllTableConstrainsCompletedEventHandler AllTableConstrainsCompleted;
        
        /// <remarks/>
        public event AllTablesInDatabaseSolOneCompletedEventHandler AllTablesInDatabaseSolOneCompleted;
        
        /// <remarks/>
        public event AllTablesInDatabaseSolTwoCompletedEventHandler AllTablesInDatabaseSolTwoCompleted;
        
        /// <remarks/>
        public event AllColEmpTableSolOneCompletedEventHandler AllColEmpTableSolOneCompleted;
        
        /// <remarks/>
        public event AllColEmpTableSolTwoCompletedEventHandler AllColEmpTableSolTwoCompleted;
        
        /// <remarks/>
        public event ShowFileCompletedEventHandler ShowFileCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/CreateEmployee", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee CreateEmployee(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            object[] results = this.Invoke("CreateEmployee", new object[] {
                        no,
                        FirstName,
                        lastName,
                        jobTitle,
                        address,
                        phoneNumber,
                        email,
                        ssn});
            return ((Employee)(results[0]));
        }
        
        /// <remarks/>
        public void CreateEmployeeAsync(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            this.CreateEmployeeAsync(no, FirstName, lastName, jobTitle, address, phoneNumber, email, ssn, null);
        }
        
        /// <remarks/>
        public void CreateEmployeeAsync(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn, object userState) {
            if ((this.CreateEmployeeOperationCompleted == null)) {
                this.CreateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateEmployeeOperationCompleted);
            }
            this.InvokeAsync("CreateEmployee", new object[] {
                        no,
                        FirstName,
                        lastName,
                        jobTitle,
                        address,
                        phoneNumber,
                        email,
                        ssn}, this.CreateEmployeeOperationCompleted, userState);
        }
        
        private void OnCreateEmployeeOperationCompleted(object arg) {
            if ((this.CreateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateEmployeeCompleted(this, new CreateEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/FindEmployee", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee FindEmployee(string no) {
            object[] results = this.Invoke("FindEmployee", new object[] {
                        no});
            return ((Employee)(results[0]));
        }
        
        /// <remarks/>
        public void FindEmployeeAsync(string no) {
            this.FindEmployeeAsync(no, null);
        }
        
        /// <remarks/>
        public void FindEmployeeAsync(string no, object userState) {
            if ((this.FindEmployeeOperationCompleted == null)) {
                this.FindEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindEmployeeOperationCompleted);
            }
            this.InvokeAsync("FindEmployee", new object[] {
                        no}, this.FindEmployeeOperationCompleted, userState);
        }
        
        private void OnFindEmployeeOperationCompleted(object arg) {
            if ((this.FindEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindEmployeeCompleted(this, new FindEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/UpdateEmployee", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Employee UpdateEmployee(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email) {
            object[] results = this.Invoke("UpdateEmployee", new object[] {
                        no,
                        firstName,
                        lastName,
                        jobTitle,
                        address,
                        phoneNumber,
                        email});
            return ((Employee)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateEmployeeAsync(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email) {
            this.UpdateEmployeeAsync(no, firstName, lastName, jobTitle, address, phoneNumber, email, null);
        }
        
        /// <remarks/>
        public void UpdateEmployeeAsync(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email, object userState) {
            if ((this.UpdateEmployeeOperationCompleted == null)) {
                this.UpdateEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateEmployeeOperationCompleted);
            }
            this.InvokeAsync("UpdateEmployee", new object[] {
                        no,
                        firstName,
                        lastName,
                        jobTitle,
                        address,
                        phoneNumber,
                        email}, this.UpdateEmployeeOperationCompleted, userState);
        }
        
        private void OnUpdateEmployeeOperationCompleted(object arg) {
            if ((this.UpdateEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateEmployeeCompleted(this, new UpdateEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/DeleteEmployee", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool DeleteEmployee(string no) {
            object[] results = this.Invoke("DeleteEmployee", new object[] {
                        no});
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteEmployeeAsync(string no) {
            this.DeleteEmployeeAsync(no, null);
        }
        
        /// <remarks/>
        public void DeleteEmployeeAsync(string no, object userState) {
            if ((this.DeleteEmployeeOperationCompleted == null)) {
                this.DeleteEmployeeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteEmployeeOperationCompleted);
            }
            this.InvokeAsync("DeleteEmployee", new object[] {
                        no}, this.DeleteEmployeeOperationCompleted, userState);
        }
        
        private void OnDeleteEmployeeOperationCompleted(object arg) {
            if ((this.DeleteEmployeeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteEmployeeCompleted(this, new DeleteEmployeeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/ShowContentOfCronus", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ShowContentOfCronus() {
            object[] results = this.Invoke("ShowContentOfCronus", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ShowContentOfCronusAsync() {
            this.ShowContentOfCronusAsync(null);
        }
        
        /// <remarks/>
        public void ShowContentOfCronusAsync(object userState) {
            if ((this.ShowContentOfCronusOperationCompleted == null)) {
                this.ShowContentOfCronusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowContentOfCronusOperationCompleted);
            }
            this.InvokeAsync("ShowContentOfCronus", new object[0], this.ShowContentOfCronusOperationCompleted, userState);
        }
        
        private void OnShowContentOfCronusOperationCompleted(object arg) {
            if ((this.ShowContentOfCronusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowContentOfCronusCompleted(this, new ShowContentOfCronusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/EmployeeAndRelatives", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable EmployeeAndRelatives() {
            object[] results = this.Invoke("EmployeeAndRelatives", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void EmployeeAndRelativesAsync() {
            this.EmployeeAndRelativesAsync(null);
        }
        
        /// <remarks/>
        public void EmployeeAndRelativesAsync(object userState) {
            if ((this.EmployeeAndRelativesOperationCompleted == null)) {
                this.EmployeeAndRelativesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEmployeeAndRelativesOperationCompleted);
            }
            this.InvokeAsync("EmployeeAndRelatives", new object[0], this.EmployeeAndRelativesOperationCompleted, userState);
        }
        
        private void OnEmployeeAndRelativesOperationCompleted(object arg) {
            if ((this.EmployeeAndRelativesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EmployeeAndRelativesCompleted(this, new EmployeeAndRelativesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/ShowSickEmployees2004", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ShowSickEmployees2004() {
            object[] results = this.Invoke("ShowSickEmployees2004", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ShowSickEmployees2004Async() {
            this.ShowSickEmployees2004Async(null);
        }
        
        /// <remarks/>
        public void ShowSickEmployees2004Async(object userState) {
            if ((this.ShowSickEmployees2004OperationCompleted == null)) {
                this.ShowSickEmployees2004OperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowSickEmployees2004OperationCompleted);
            }
            this.InvokeAsync("ShowSickEmployees2004", new object[0], this.ShowSickEmployees2004OperationCompleted, userState);
        }
        
        private void OnShowSickEmployees2004OperationCompleted(object arg) {
            if ((this.ShowSickEmployees2004Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowSickEmployees2004Completed(this, new ShowSickEmployees2004CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/MostAbsentEmployees", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable MostAbsentEmployees() {
            object[] results = this.Invoke("MostAbsentEmployees", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void MostAbsentEmployeesAsync() {
            this.MostAbsentEmployeesAsync(null);
        }
        
        /// <remarks/>
        public void MostAbsentEmployeesAsync(object userState) {
            if ((this.MostAbsentEmployeesOperationCompleted == null)) {
                this.MostAbsentEmployeesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnMostAbsentEmployeesOperationCompleted);
            }
            this.InvokeAsync("MostAbsentEmployees", new object[0], this.MostAbsentEmployeesOperationCompleted, userState);
        }
        
        private void OnMostAbsentEmployeesOperationCompleted(object arg) {
            if ((this.MostAbsentEmployeesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.MostAbsentEmployeesCompleted(this, new MostAbsentEmployeesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/AllKeys", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AllKeys() {
            object[] results = this.Invoke("AllKeys", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AllKeysAsync() {
            this.AllKeysAsync(null);
        }
        
        /// <remarks/>
        public void AllKeysAsync(object userState) {
            if ((this.AllKeysOperationCompleted == null)) {
                this.AllKeysOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllKeysOperationCompleted);
            }
            this.InvokeAsync("AllKeys", new object[0], this.AllKeysOperationCompleted, userState);
        }
        
        private void OnAllKeysOperationCompleted(object arg) {
            if ((this.AllKeysCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllKeysCompleted(this, new AllKeysCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/AllIndexes", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AllIndexes() {
            object[] results = this.Invoke("AllIndexes", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AllIndexesAsync() {
            this.AllIndexesAsync(null);
        }
        
        /// <remarks/>
        public void AllIndexesAsync(object userState) {
            if ((this.AllIndexesOperationCompleted == null)) {
                this.AllIndexesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllIndexesOperationCompleted);
            }
            this.InvokeAsync("AllIndexes", new object[0], this.AllIndexesOperationCompleted, userState);
        }
        
        private void OnAllIndexesOperationCompleted(object arg) {
            if ((this.AllIndexesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllIndexesCompleted(this, new AllIndexesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/AllTableConstrains", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AllTableConstrains() {
            object[] results = this.Invoke("AllTableConstrains", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AllTableConstrainsAsync() {
            this.AllTableConstrainsAsync(null);
        }
        
        /// <remarks/>
        public void AllTableConstrainsAsync(object userState) {
            if ((this.AllTableConstrainsOperationCompleted == null)) {
                this.AllTableConstrainsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllTableConstrainsOperationCompleted);
            }
            this.InvokeAsync("AllTableConstrains", new object[0], this.AllTableConstrainsOperationCompleted, userState);
        }
        
        private void OnAllTableConstrainsOperationCompleted(object arg) {
            if ((this.AllTableConstrainsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllTableConstrainsCompleted(this, new AllTableConstrainsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/AllTablesInDatabaseSolOne", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AllTablesInDatabaseSolOne() {
            object[] results = this.Invoke("AllTablesInDatabaseSolOne", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AllTablesInDatabaseSolOneAsync() {
            this.AllTablesInDatabaseSolOneAsync(null);
        }
        
        /// <remarks/>
        public void AllTablesInDatabaseSolOneAsync(object userState) {
            if ((this.AllTablesInDatabaseSolOneOperationCompleted == null)) {
                this.AllTablesInDatabaseSolOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllTablesInDatabaseSolOneOperationCompleted);
            }
            this.InvokeAsync("AllTablesInDatabaseSolOne", new object[0], this.AllTablesInDatabaseSolOneOperationCompleted, userState);
        }
        
        private void OnAllTablesInDatabaseSolOneOperationCompleted(object arg) {
            if ((this.AllTablesInDatabaseSolOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllTablesInDatabaseSolOneCompleted(this, new AllTablesInDatabaseSolOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/AllTablesInDatabaseSolTwo", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AllTablesInDatabaseSolTwo() {
            object[] results = this.Invoke("AllTablesInDatabaseSolTwo", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AllTablesInDatabaseSolTwoAsync() {
            this.AllTablesInDatabaseSolTwoAsync(null);
        }
        
        /// <remarks/>
        public void AllTablesInDatabaseSolTwoAsync(object userState) {
            if ((this.AllTablesInDatabaseSolTwoOperationCompleted == null)) {
                this.AllTablesInDatabaseSolTwoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllTablesInDatabaseSolTwoOperationCompleted);
            }
            this.InvokeAsync("AllTablesInDatabaseSolTwo", new object[0], this.AllTablesInDatabaseSolTwoOperationCompleted, userState);
        }
        
        private void OnAllTablesInDatabaseSolTwoOperationCompleted(object arg) {
            if ((this.AllTablesInDatabaseSolTwoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllTablesInDatabaseSolTwoCompleted(this, new AllTablesInDatabaseSolTwoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/AllColEmpTableSolOne", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AllColEmpTableSolOne() {
            object[] results = this.Invoke("AllColEmpTableSolOne", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AllColEmpTableSolOneAsync() {
            this.AllColEmpTableSolOneAsync(null);
        }
        
        /// <remarks/>
        public void AllColEmpTableSolOneAsync(object userState) {
            if ((this.AllColEmpTableSolOneOperationCompleted == null)) {
                this.AllColEmpTableSolOneOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllColEmpTableSolOneOperationCompleted);
            }
            this.InvokeAsync("AllColEmpTableSolOne", new object[0], this.AllColEmpTableSolOneOperationCompleted, userState);
        }
        
        private void OnAllColEmpTableSolOneOperationCompleted(object arg) {
            if ((this.AllColEmpTableSolOneCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllColEmpTableSolOneCompleted(this, new AllColEmpTableSolOneCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/AllColEmpTableSolTwo", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable AllColEmpTableSolTwo() {
            object[] results = this.Invoke("AllColEmpTableSolTwo", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void AllColEmpTableSolTwoAsync() {
            this.AllColEmpTableSolTwoAsync(null);
        }
        
        /// <remarks/>
        public void AllColEmpTableSolTwoAsync(object userState) {
            if ((this.AllColEmpTableSolTwoOperationCompleted == null)) {
                this.AllColEmpTableSolTwoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAllColEmpTableSolTwoOperationCompleted);
            }
            this.InvokeAsync("AllColEmpTableSolTwo", new object[0], this.AllColEmpTableSolTwoOperationCompleted, userState);
        }
        
        private void OnAllColEmpTableSolTwoOperationCompleted(object arg) {
            if ((this.AllColEmpTableSolTwoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AllColEmpTableSolTwoCompleted(this, new AllColEmpTableSolTwoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/ShowFile", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ShowFile(string fileName) {
            object[] results = this.Invoke("ShowFile", new object[] {
                        fileName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ShowFileAsync(string fileName) {
            this.ShowFileAsync(fileName, null);
        }
        
        /// <remarks/>
        public void ShowFileAsync(string fileName, object userState) {
            if ((this.ShowFileOperationCompleted == null)) {
                this.ShowFileOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowFileOperationCompleted);
            }
            this.InvokeAsync("ShowFile", new object[] {
                        fileName}, this.ShowFileOperationCompleted, userState);
        }
        
        private void OnShowFileOperationCompleted(object arg) {
            if ((this.ShowFileCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowFileCompleted(this, new ShowFileCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class Employee {
        
        private string noField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string jobTitleField;
        
        private string addressField;
        
        private string phoneNumberField;
        
        private string ssnField;
        
        private string emailField;
        
        /// <remarks/>
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
            }
        }
        
        /// <remarks/>
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        public string Ssn {
            get {
                return this.ssnField;
            }
            set {
                this.ssnField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CreateEmployeeCompletedEventHandler(object sender, CreateEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void FindEmployeeCompletedEventHandler(object sender, FindEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UpdateEmployeeCompletedEventHandler(object sender, UpdateEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Employee Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Employee)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void DeleteEmployeeCompletedEventHandler(object sender, DeleteEmployeeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteEmployeeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteEmployeeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ShowContentOfCronusCompletedEventHandler(object sender, ShowContentOfCronusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowContentOfCronusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowContentOfCronusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void EmployeeAndRelativesCompletedEventHandler(object sender, EmployeeAndRelativesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EmployeeAndRelativesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EmployeeAndRelativesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ShowSickEmployees2004CompletedEventHandler(object sender, ShowSickEmployees2004CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowSickEmployees2004CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowSickEmployees2004CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void MostAbsentEmployeesCompletedEventHandler(object sender, MostAbsentEmployeesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class MostAbsentEmployeesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal MostAbsentEmployeesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AllKeysCompletedEventHandler(object sender, AllKeysCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllKeysCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllKeysCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AllIndexesCompletedEventHandler(object sender, AllIndexesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllIndexesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllIndexesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AllTableConstrainsCompletedEventHandler(object sender, AllTableConstrainsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllTableConstrainsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllTableConstrainsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AllTablesInDatabaseSolOneCompletedEventHandler(object sender, AllTablesInDatabaseSolOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllTablesInDatabaseSolOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllTablesInDatabaseSolOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AllTablesInDatabaseSolTwoCompletedEventHandler(object sender, AllTablesInDatabaseSolTwoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllTablesInDatabaseSolTwoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllTablesInDatabaseSolTwoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AllColEmpTableSolOneCompletedEventHandler(object sender, AllColEmpTableSolOneCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllColEmpTableSolOneCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllColEmpTableSolOneCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void AllColEmpTableSolTwoCompletedEventHandler(object sender, AllColEmpTableSolTwoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AllColEmpTableSolTwoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AllColEmpTableSolTwoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ShowFileCompletedEventHandler(object sender, ShowFileCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowFileCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowFileCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591