//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.WebAssignment1Soap")]
    public interface WebAssignment1Soap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowFile", ReplyAction="*")]
        ConsoleApp.ServiceReference.ShowFileResponse ShowFile(ConsoleApp.ServiceReference.ShowFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleApp.ServiceReference.ShowFileResponse> ShowFileAsync(ConsoleApp.ServiceReference.ShowFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowFile", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp.ServiceReference.ShowFileRequestBody Body;
        
        public ShowFileRequest() {
        }
        
        public ShowFileRequest(ConsoleApp.ServiceReference.ShowFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public ShowFileRequestBody() {
        }
        
        public ShowFileRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowFileResponse", Namespace="http://tempuri.org/", Order=0)]
        public ConsoleApp.ServiceReference.ShowFileResponseBody Body;
        
        public ShowFileResponse() {
        }
        
        public ShowFileResponse(ConsoleApp.ServiceReference.ShowFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ShowFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowFileResult;
        
        public ShowFileResponseBody() {
        }
        
        public ShowFileResponseBody(string ShowFileResult) {
            this.ShowFileResult = ShowFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebAssignment1SoapChannel : ConsoleApp.ServiceReference.WebAssignment1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebAssignment1SoapClient : System.ServiceModel.ClientBase<ConsoleApp.ServiceReference.WebAssignment1Soap>, ConsoleApp.ServiceReference.WebAssignment1Soap {
        
        public WebAssignment1SoapClient() {
        }
        
        public WebAssignment1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebAssignment1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAssignment1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAssignment1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleApp.ServiceReference.ShowFileResponse ConsoleApp.ServiceReference.WebAssignment1Soap.ShowFile(ConsoleApp.ServiceReference.ShowFileRequest request) {
            return base.Channel.ShowFile(request);
        }
        
        public string ShowFile(string fileName) {
            ConsoleApp.ServiceReference.ShowFileRequest inValue = new ConsoleApp.ServiceReference.ShowFileRequest();
            inValue.Body = new ConsoleApp.ServiceReference.ShowFileRequestBody();
            inValue.Body.fileName = fileName;
            ConsoleApp.ServiceReference.ShowFileResponse retVal = ((ConsoleApp.ServiceReference.WebAssignment1Soap)(this)).ShowFile(inValue);
            return retVal.Body.ShowFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleApp.ServiceReference.ShowFileResponse> ConsoleApp.ServiceReference.WebAssignment1Soap.ShowFileAsync(ConsoleApp.ServiceReference.ShowFileRequest request) {
            return base.Channel.ShowFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp.ServiceReference.ShowFileResponse> ShowFileAsync(string fileName) {
            ConsoleApp.ServiceReference.ShowFileRequest inValue = new ConsoleApp.ServiceReference.ShowFileRequest();
            inValue.Body = new ConsoleApp.ServiceReference.ShowFileRequestBody();
            inValue.Body.fileName = fileName;
            return ((ConsoleApp.ServiceReference.WebAssignment1Soap)(this)).ShowFileAsync(inValue);
        }
    }
}
