//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleAppWebService.RefService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://grupp2.ics.lu.se/", ConfigurationName="RefService.WebServiceAssignmentSoap")]
    public interface WebServiceAssignmentSoap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://grupp2.ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowFile", ReplyAction="*")]
        ConsoleAppWebService.RefService.ShowFileResponse ShowFile(ConsoleAppWebService.RefService.ShowFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ConsoleAppWebService.RefService.ShowFileResponse> ShowFileAsync(ConsoleAppWebService.RefService.ShowFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowFile", Namespace="http://grupp2.ics.lu.se/", Order=0)]
        public ConsoleAppWebService.RefService.ShowFileRequestBody Body;
        
        public ShowFileRequest() {
        }
        
        public ShowFileRequest(ConsoleAppWebService.RefService.ShowFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class ShowFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public ShowFileRequestBody() {
        }
        
        public ShowFileRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowFileResponse", Namespace="http://grupp2.ics.lu.se/", Order=0)]
        public ConsoleAppWebService.RefService.ShowFileResponseBody Body;
        
        public ShowFileResponse() {
        }
        
        public ShowFileResponse(ConsoleAppWebService.RefService.ShowFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class ShowFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowFileResult;
        
        public ShowFileResponseBody() {
        }
        
        public ShowFileResponseBody(string ShowFileResult) {
            this.ShowFileResult = ShowFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAssignmentSoapChannel : ConsoleAppWebService.RefService.WebServiceAssignmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAssignmentSoapClient : System.ServiceModel.ClientBase<ConsoleAppWebService.RefService.WebServiceAssignmentSoap>, ConsoleAppWebService.RefService.WebServiceAssignmentSoap {
        
        public WebServiceAssignmentSoapClient() {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAssignmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ConsoleAppWebService.RefService.ShowFileResponse ConsoleAppWebService.RefService.WebServiceAssignmentSoap.ShowFile(ConsoleAppWebService.RefService.ShowFileRequest request) {
            return base.Channel.ShowFile(request);
        }
        
        public string ShowFile(string fileName) {
            ConsoleAppWebService.RefService.ShowFileRequest inValue = new ConsoleAppWebService.RefService.ShowFileRequest();
            inValue.Body = new ConsoleAppWebService.RefService.ShowFileRequestBody();
            inValue.Body.fileName = fileName;
            ConsoleAppWebService.RefService.ShowFileResponse retVal = ((ConsoleAppWebService.RefService.WebServiceAssignmentSoap)(this)).ShowFile(inValue);
            return retVal.Body.ShowFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ConsoleAppWebService.RefService.ShowFileResponse> ConsoleAppWebService.RefService.WebServiceAssignmentSoap.ShowFileAsync(ConsoleAppWebService.RefService.ShowFileRequest request) {
            return base.Channel.ShowFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ConsoleAppWebService.RefService.ShowFileResponse> ShowFileAsync(string fileName) {
            ConsoleAppWebService.RefService.ShowFileRequest inValue = new ConsoleAppWebService.RefService.ShowFileRequest();
            inValue.Body = new ConsoleAppWebService.RefService.ShowFileRequestBody();
            inValue.Body.fileName = fileName;
            return ((ConsoleAppWebService.RefService.WebServiceAssignmentSoap)(this)).ShowFileAsync(inValue);
        }
    }
}
