//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormsWebService.OpenFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://grupp2.ics.lu.se/", ConfigurationName="OpenFileService.WebServiceAssignmentSoap")]
    public interface WebServiceAssignmentSoap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://grupp2.ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowFile", ReplyAction="*")]
        FormsWebService.OpenFileService.ShowFileResponse ShowFile(FormsWebService.OpenFileService.ShowFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowFile", ReplyAction="*")]
        System.Threading.Tasks.Task<FormsWebService.OpenFileService.ShowFileResponse> ShowFileAsync(FormsWebService.OpenFileService.ShowFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowFile", Namespace="http://grupp2.ics.lu.se/", Order=0)]
        public FormsWebService.OpenFileService.ShowFileRequestBody Body;
        
        public ShowFileRequest() {
        }
        
        public ShowFileRequest(FormsWebService.OpenFileService.ShowFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class ShowFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public ShowFileRequestBody() {
        }
        
        public ShowFileRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowFileResponse", Namespace="http://grupp2.ics.lu.se/", Order=0)]
        public FormsWebService.OpenFileService.ShowFileResponseBody Body;
        
        public ShowFileResponse() {
        }
        
        public ShowFileResponse(FormsWebService.OpenFileService.ShowFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class ShowFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowFileResult;
        
        public ShowFileResponseBody() {
        }
        
        public ShowFileResponseBody(string ShowFileResult) {
            this.ShowFileResult = ShowFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAssignmentSoapChannel : FormsWebService.OpenFileService.WebServiceAssignmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAssignmentSoapClient : System.ServiceModel.ClientBase<FormsWebService.OpenFileService.WebServiceAssignmentSoap>, FormsWebService.OpenFileService.WebServiceAssignmentSoap {
        
        public WebServiceAssignmentSoapClient() {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAssignmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FormsWebService.OpenFileService.ShowFileResponse FormsWebService.OpenFileService.WebServiceAssignmentSoap.ShowFile(FormsWebService.OpenFileService.ShowFileRequest request) {
            return base.Channel.ShowFile(request);
        }
        
        public string ShowFile(string fileName) {
            FormsWebService.OpenFileService.ShowFileRequest inValue = new FormsWebService.OpenFileService.ShowFileRequest();
            inValue.Body = new FormsWebService.OpenFileService.ShowFileRequestBody();
            inValue.Body.fileName = fileName;
            FormsWebService.OpenFileService.ShowFileResponse retVal = ((FormsWebService.OpenFileService.WebServiceAssignmentSoap)(this)).ShowFile(inValue);
            return retVal.Body.ShowFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FormsWebService.OpenFileService.ShowFileResponse> FormsWebService.OpenFileService.WebServiceAssignmentSoap.ShowFileAsync(FormsWebService.OpenFileService.ShowFileRequest request) {
            return base.Channel.ShowFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<FormsWebService.OpenFileService.ShowFileResponse> ShowFileAsync(string fileName) {
            FormsWebService.OpenFileService.ShowFileRequest inValue = new FormsWebService.OpenFileService.ShowFileRequest();
            inValue.Body = new FormsWebService.OpenFileService.ShowFileRequestBody();
            inValue.Body.fileName = fileName;
            return ((FormsWebService.OpenFileService.WebServiceAssignmentSoap)(this)).ShowFileAsync(inValue);
        }
    }
}
