//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ProgramKonstruktion.SqlWebReference {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SqlWebServiceSoap", Namespace="http://grupp2.ics.lu.se/")]
    public partial class SqlWebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTenantBookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowAllBookingsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetListOfStoragesOperationCompleted;
        
        private System.Threading.SendOrPostCallback FindStorageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowAllStoragesOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SqlWebService() {
            this.Url = global::ProgramKonstruktion.Properties.Settings.Default.ProgramKonstruktion_SqlWebReference_SqlWebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTenantBookingsCompletedEventHandler GetTenantBookingsCompleted;
        
        /// <remarks/>
        public event ShowAllBookingsCompletedEventHandler ShowAllBookingsCompleted;
        
        /// <remarks/>
        public event GetListOfStoragesCompletedEventHandler GetListOfStoragesCompleted;
        
        /// <remarks/>
        public event FindStorageCompletedEventHandler FindStorageCompleted;
        
        /// <remarks/>
        public event ShowAllStoragesCompletedEventHandler ShowAllStoragesCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/GetTenantBookings", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Tenant[] GetTenantBookings() {
            object[] results = this.Invoke("GetTenantBookings", new object[0]);
            return ((Tenant[])(results[0]));
        }
        
        /// <remarks/>
        public void GetTenantBookingsAsync() {
            this.GetTenantBookingsAsync(null);
        }
        
        /// <remarks/>
        public void GetTenantBookingsAsync(object userState) {
            if ((this.GetTenantBookingsOperationCompleted == null)) {
                this.GetTenantBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTenantBookingsOperationCompleted);
            }
            this.InvokeAsync("GetTenantBookings", new object[0], this.GetTenantBookingsOperationCompleted, userState);
        }
        
        private void OnGetTenantBookingsOperationCompleted(object arg) {
            if ((this.GetTenantBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTenantBookingsCompleted(this, new GetTenantBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/ShowAllBookings", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ShowAllBookings() {
            object[] results = this.Invoke("ShowAllBookings", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ShowAllBookingsAsync() {
            this.ShowAllBookingsAsync(null);
        }
        
        /// <remarks/>
        public void ShowAllBookingsAsync(object userState) {
            if ((this.ShowAllBookingsOperationCompleted == null)) {
                this.ShowAllBookingsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowAllBookingsOperationCompleted);
            }
            this.InvokeAsync("ShowAllBookings", new object[0], this.ShowAllBookingsOperationCompleted, userState);
        }
        
        private void OnShowAllBookingsOperationCompleted(object arg) {
            if ((this.ShowAllBookingsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowAllBookingsCompleted(this, new ShowAllBookingsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/GetListOfStorages", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Storage[] GetListOfStorages() {
            object[] results = this.Invoke("GetListOfStorages", new object[0]);
            return ((Storage[])(results[0]));
        }
        
        /// <remarks/>
        public void GetListOfStoragesAsync() {
            this.GetListOfStoragesAsync(null);
        }
        
        /// <remarks/>
        public void GetListOfStoragesAsync(object userState) {
            if ((this.GetListOfStoragesOperationCompleted == null)) {
                this.GetListOfStoragesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetListOfStoragesOperationCompleted);
            }
            this.InvokeAsync("GetListOfStorages", new object[0], this.GetListOfStoragesOperationCompleted, userState);
        }
        
        private void OnGetListOfStoragesOperationCompleted(object arg) {
            if ((this.GetListOfStoragesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetListOfStoragesCompleted(this, new GetListOfStoragesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/FindStorage", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Storage FindStorage(string nbr) {
            object[] results = this.Invoke("FindStorage", new object[] {
                        nbr});
            return ((Storage)(results[0]));
        }
        
        /// <remarks/>
        public void FindStorageAsync(string nbr) {
            this.FindStorageAsync(nbr, null);
        }
        
        /// <remarks/>
        public void FindStorageAsync(string nbr, object userState) {
            if ((this.FindStorageOperationCompleted == null)) {
                this.FindStorageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFindStorageOperationCompleted);
            }
            this.InvokeAsync("FindStorage", new object[] {
                        nbr}, this.FindStorageOperationCompleted, userState);
        }
        
        private void OnFindStorageOperationCompleted(object arg) {
            if ((this.FindStorageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FindStorageCompleted(this, new FindStorageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://grupp2.ics.lu.se/ShowAllStorages", RequestNamespace="http://grupp2.ics.lu.se/", ResponseNamespace="http://grupp2.ics.lu.se/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable ShowAllStorages() {
            object[] results = this.Invoke("ShowAllStorages", new object[0]);
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void ShowAllStoragesAsync() {
            this.ShowAllStoragesAsync(null);
        }
        
        /// <remarks/>
        public void ShowAllStoragesAsync(object userState) {
            if ((this.ShowAllStoragesOperationCompleted == null)) {
                this.ShowAllStoragesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowAllStoragesOperationCompleted);
            }
            this.InvokeAsync("ShowAllStorages", new object[0], this.ShowAllStoragesOperationCompleted, userState);
        }
        
        private void OnShowAllStoragesOperationCompleted(object arg) {
            if ((this.ShowAllStoragesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowAllStoragesCompleted(this, new ShowAllStoragesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class Tenant {
        
        private string ssnField;
        
        private string nameField;
        
        private string phoneNbrField;
        
        private string emailField;
        
        private string storageNbrField;
        
        private System.DateTime rentDateField;
        
        private string storageAddressField;
        
        /// <remarks/>
        public string Ssn {
            get {
                return this.ssnField;
            }
            set {
                this.ssnField = value;
            }
        }
        
        /// <remarks/>
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public string PhoneNbr {
            get {
                return this.phoneNbrField;
            }
            set {
                this.phoneNbrField = value;
            }
        }
        
        /// <remarks/>
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        public string StorageNbr {
            get {
                return this.storageNbrField;
            }
            set {
                this.storageNbrField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime RentDate {
            get {
                return this.rentDateField;
            }
            set {
                this.rentDateField = value;
            }
        }
        
        /// <remarks/>
        public string StorageAddress {
            get {
                return this.storageAddressField;
            }
            set {
                this.storageAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class Storage {
        
        private string nbrField;
        
        private float priceField;
        
        private float sizeField;
        
        private string addressField;
        
        /// <remarks/>
        public string Nbr {
            get {
                return this.nbrField;
            }
            set {
                this.nbrField = value;
            }
        }
        
        /// <remarks/>
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
            }
        }
        
        /// <remarks/>
        public float Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
            }
        }
        
        /// <remarks/>
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetTenantBookingsCompletedEventHandler(object sender, GetTenantBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTenantBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTenantBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Tenant[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Tenant[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ShowAllBookingsCompletedEventHandler(object sender, ShowAllBookingsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowAllBookingsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowAllBookingsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetListOfStoragesCompletedEventHandler(object sender, GetListOfStoragesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetListOfStoragesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetListOfStoragesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Storage[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Storage[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void FindStorageCompletedEventHandler(object sender, FindStorageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FindStorageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FindStorageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Storage Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Storage)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void ShowAllStoragesCompletedEventHandler(object sender, ShowAllStoragesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowAllStoragesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowAllStoragesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591