//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramKonstruktion.SqlServiceReference {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://grupp2.ics.lu.se/", ConfigurationName="SqlServiceReference.SqlWebServiceSoap")]
    public interface SqlWebServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/GetTenantBookings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramKonstruktion.SqlServiceReference.Tenant[] GetTenantBookings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/GetTenantBookings", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.SqlServiceReference.Tenant[]> GetTenantBookingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowAllBookings", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ShowAllBookings();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowAllBookings", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowAllBookingsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/GetListOfStorages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramKonstruktion.SqlServiceReference.Storage[] GetListOfStorages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/GetListOfStorages", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.SqlServiceReference.Storage[]> GetListOfStoragesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/FindStorage", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramKonstruktion.SqlServiceReference.Storage FindStorage(string nbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/FindStorage", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.SqlServiceReference.Storage> FindStorageAsync(string nbr);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowAllStorages", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ShowAllStorages();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowAllStorages", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowAllStoragesAsync();
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class Tenant : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string ssnField;
        
        private string nameField;
        
        private string phoneNbrField;
        
        private string emailField;
        
        private string storageNbrField;
        
        private System.DateTime rentDateField;
        
        private string storageAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Ssn {
            get {
                return this.ssnField;
            }
            set {
                this.ssnField = value;
                this.RaisePropertyChanged("Ssn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PhoneNbr {
            get {
                return this.phoneNbrField;
            }
            set {
                this.phoneNbrField = value;
                this.RaisePropertyChanged("PhoneNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string StorageNbr {
            get {
                return this.storageNbrField;
            }
            set {
                this.storageNbrField = value;
                this.RaisePropertyChanged("StorageNbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime RentDate {
            get {
                return this.rentDateField;
            }
            set {
                this.rentDateField = value;
                this.RaisePropertyChanged("RentDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string StorageAddress {
            get {
                return this.storageAddressField;
            }
            set {
                this.storageAddressField = value;
                this.RaisePropertyChanged("StorageAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class Storage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nbrField;
        
        private float priceField;
        
        private float sizeField;
        
        private string addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Nbr {
            get {
                return this.nbrField;
            }
            set {
                this.nbrField = value;
                this.RaisePropertyChanged("Nbr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public float Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public float Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SqlWebServiceSoapChannel : ProgramKonstruktion.SqlServiceReference.SqlWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SqlWebServiceSoapClient : System.ServiceModel.ClientBase<ProgramKonstruktion.SqlServiceReference.SqlWebServiceSoap>, ProgramKonstruktion.SqlServiceReference.SqlWebServiceSoap {
        
        public SqlWebServiceSoapClient() {
        }
        
        public SqlWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SqlWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SqlWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProgramKonstruktion.SqlServiceReference.Tenant[] GetTenantBookings() {
            return base.Channel.GetTenantBookings();
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.SqlServiceReference.Tenant[]> GetTenantBookingsAsync() {
            return base.Channel.GetTenantBookingsAsync();
        }
        
        public System.Data.DataTable ShowAllBookings() {
            return base.Channel.ShowAllBookings();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowAllBookingsAsync() {
            return base.Channel.ShowAllBookingsAsync();
        }
        
        public ProgramKonstruktion.SqlServiceReference.Storage[] GetListOfStorages() {
            return base.Channel.GetListOfStorages();
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.SqlServiceReference.Storage[]> GetListOfStoragesAsync() {
            return base.Channel.GetListOfStoragesAsync();
        }
        
        public ProgramKonstruktion.SqlServiceReference.Storage FindStorage(string nbr) {
            return base.Channel.FindStorage(nbr);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.SqlServiceReference.Storage> FindStorageAsync(string nbr) {
            return base.Channel.FindStorageAsync(nbr);
        }
        
        public System.Data.DataTable ShowAllStorages() {
            return base.Channel.ShowAllStorages();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowAllStoragesAsync() {
            return base.Channel.ShowAllStoragesAsync();
        }
    }
}
