//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramKonstruktion.OpenFileService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://grupp2.ics.lu.se/", ConfigurationName="OpenFileService.WebServiceAssignmentSoap")]
    public interface WebServiceAssignmentSoap {
        
        // CODEGEN: Generating message contract since element name fileName from namespace http://grupp2.ics.lu.se/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowFile", ReplyAction="*")]
        ProgramKonstruktion.OpenFileService.ShowFileResponse ShowFile(ProgramKonstruktion.OpenFileService.ShowFileRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://grupp2.ics.lu.se/ShowFile", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.OpenFileService.ShowFileResponse> ShowFileAsync(ProgramKonstruktion.OpenFileService.ShowFileRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowFileRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowFile", Namespace="http://grupp2.ics.lu.se/", Order=0)]
        public ProgramKonstruktion.OpenFileService.ShowFileRequestBody Body;
        
        public ShowFileRequest() {
        }
        
        public ShowFileRequest(ProgramKonstruktion.OpenFileService.ShowFileRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class ShowFileRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileName;
        
        public ShowFileRequestBody() {
        }
        
        public ShowFileRequestBody(string fileName) {
            this.fileName = fileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ShowFileResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ShowFileResponse", Namespace="http://grupp2.ics.lu.se/", Order=0)]
        public ProgramKonstruktion.OpenFileService.ShowFileResponseBody Body;
        
        public ShowFileResponse() {
        }
        
        public ShowFileResponse(ProgramKonstruktion.OpenFileService.ShowFileResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://grupp2.ics.lu.se/")]
    public partial class ShowFileResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ShowFileResult;
        
        public ShowFileResponseBody() {
        }
        
        public ShowFileResponseBody(string ShowFileResult) {
            this.ShowFileResult = ShowFileResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceAssignmentSoapChannel : ProgramKonstruktion.OpenFileService.WebServiceAssignmentSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceAssignmentSoapClient : System.ServiceModel.ClientBase<ProgramKonstruktion.OpenFileService.WebServiceAssignmentSoap>, ProgramKonstruktion.OpenFileService.WebServiceAssignmentSoap {
        
        public WebServiceAssignmentSoapClient() {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAssignmentSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceAssignmentSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramKonstruktion.OpenFileService.ShowFileResponse ProgramKonstruktion.OpenFileService.WebServiceAssignmentSoap.ShowFile(ProgramKonstruktion.OpenFileService.ShowFileRequest request) {
            return base.Channel.ShowFile(request);
        }
        
        public string ShowFile(string fileName) {
            ProgramKonstruktion.OpenFileService.ShowFileRequest inValue = new ProgramKonstruktion.OpenFileService.ShowFileRequest();
            inValue.Body = new ProgramKonstruktion.OpenFileService.ShowFileRequestBody();
            inValue.Body.fileName = fileName;
            ProgramKonstruktion.OpenFileService.ShowFileResponse retVal = ((ProgramKonstruktion.OpenFileService.WebServiceAssignmentSoap)(this)).ShowFile(inValue);
            return retVal.Body.ShowFileResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramKonstruktion.OpenFileService.ShowFileResponse> ProgramKonstruktion.OpenFileService.WebServiceAssignmentSoap.ShowFileAsync(ProgramKonstruktion.OpenFileService.ShowFileRequest request) {
            return base.Channel.ShowFileAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.OpenFileService.ShowFileResponse> ShowFileAsync(string fileName) {
            ProgramKonstruktion.OpenFileService.ShowFileRequest inValue = new ProgramKonstruktion.OpenFileService.ShowFileRequest();
            inValue.Body = new ProgramKonstruktion.OpenFileService.ShowFileRequestBody();
            inValue.Body.fileName = fileName;
            return ((ProgramKonstruktion.OpenFileService.WebServiceAssignmentSoap)(this)).ShowFileAsync(inValue);
        }
    }
}
