//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramKonstruktion.NewServWebMeta {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NewServWebMeta.WebServiceERP12Soap")]
    public interface WebServiceERP12Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramKonstruktion.NewServWebMeta.Employee CreateEmployee(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.NewServWebMeta.Employee> CreateEmployeeAsync(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramKonstruktion.NewServWebMeta.Employee FindEmployee(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.NewServWebMeta.Employee> FindEmployeeAsync(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ProgramKonstruktion.NewServWebMeta.Employee UpdateEmployee(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.NewServWebMeta.Employee> UpdateEmployeeAsync(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool DeleteEmployee(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(string no);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowContentOfCronus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ShowContentOfCronus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowContentOfCronus", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowContentOfCronusAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeAndRelatives", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable EmployeeAndRelatives();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EmployeeAndRelatives", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> EmployeeAndRelativesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowSickEmployees2004", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable ShowSickEmployees2004();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowSickEmployees2004", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> ShowSickEmployees2004Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostAbsentEmployees", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable MostAbsentEmployees();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MostAbsentEmployees", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> MostAbsentEmployeesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllKeys", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllKeys();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllKeys", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllKeysAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllIndexes", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllIndexes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllIndexes", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllIndexesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTableConstrains", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllTableConstrains();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTableConstrains", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllTableConstrainsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTablesInDatabaseSolOne", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllTablesInDatabaseSolOne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTablesInDatabaseSolOne", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllTablesInDatabaseSolOneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTablesInDatabaseSolTwo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllTablesInDatabaseSolTwo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllTablesInDatabaseSolTwo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllTablesInDatabaseSolTwoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllColEmpTableSolOne", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllColEmpTableSolOne();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllColEmpTableSolOne", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllColEmpTableSolOneAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllColEmpTableSolTwo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable AllColEmpTableSolTwo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllColEmpTableSolTwo", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> AllColEmpTableSolTwoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowFile", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ShowFile(string fileName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ShowFile", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ShowFileAsync(string fileName);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Employee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string noField;
        
        private string firstNameField;
        
        private string lastNameField;
        
        private string jobTitleField;
        
        private string addressField;
        
        private string phoneNumberField;
        
        private string ssnField;
        
        private string emailField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string No {
            get {
                return this.noField;
            }
            set {
                this.noField = value;
                this.RaisePropertyChanged("No");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string JobTitle {
            get {
                return this.jobTitleField;
            }
            set {
                this.jobTitleField = value;
                this.RaisePropertyChanged("JobTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string PhoneNumber {
            get {
                return this.phoneNumberField;
            }
            set {
                this.phoneNumberField = value;
                this.RaisePropertyChanged("PhoneNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Ssn {
            get {
                return this.ssnField;
            }
            set {
                this.ssnField = value;
                this.RaisePropertyChanged("Ssn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("Email");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceERP12SoapChannel : ProgramKonstruktion.NewServWebMeta.WebServiceERP12Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceERP12SoapClient : System.ServiceModel.ClientBase<ProgramKonstruktion.NewServWebMeta.WebServiceERP12Soap>, ProgramKonstruktion.NewServWebMeta.WebServiceERP12Soap {
        
        public WebServiceERP12SoapClient() {
        }
        
        public WebServiceERP12SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceERP12SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceERP12SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceERP12SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ProgramKonstruktion.NewServWebMeta.Employee CreateEmployee(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            return base.Channel.CreateEmployee(no, FirstName, lastName, jobTitle, address, phoneNumber, email, ssn);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.NewServWebMeta.Employee> CreateEmployeeAsync(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            return base.Channel.CreateEmployeeAsync(no, FirstName, lastName, jobTitle, address, phoneNumber, email, ssn);
        }
        
        public ProgramKonstruktion.NewServWebMeta.Employee FindEmployee(string no) {
            return base.Channel.FindEmployee(no);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.NewServWebMeta.Employee> FindEmployeeAsync(string no) {
            return base.Channel.FindEmployeeAsync(no);
        }
        
        public ProgramKonstruktion.NewServWebMeta.Employee UpdateEmployee(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email) {
            return base.Channel.UpdateEmployee(no, firstName, lastName, jobTitle, address, phoneNumber, email);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.NewServWebMeta.Employee> UpdateEmployeeAsync(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email) {
            return base.Channel.UpdateEmployeeAsync(no, firstName, lastName, jobTitle, address, phoneNumber, email);
        }
        
        public bool DeleteEmployee(string no) {
            return base.Channel.DeleteEmployee(no);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteEmployeeAsync(string no) {
            return base.Channel.DeleteEmployeeAsync(no);
        }
        
        public System.Data.DataTable ShowContentOfCronus() {
            return base.Channel.ShowContentOfCronus();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowContentOfCronusAsync() {
            return base.Channel.ShowContentOfCronusAsync();
        }
        
        public System.Data.DataTable EmployeeAndRelatives() {
            return base.Channel.EmployeeAndRelatives();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> EmployeeAndRelativesAsync() {
            return base.Channel.EmployeeAndRelativesAsync();
        }
        
        public System.Data.DataTable ShowSickEmployees2004() {
            return base.Channel.ShowSickEmployees2004();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ShowSickEmployees2004Async() {
            return base.Channel.ShowSickEmployees2004Async();
        }
        
        public System.Data.DataTable MostAbsentEmployees() {
            return base.Channel.MostAbsentEmployees();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> MostAbsentEmployeesAsync() {
            return base.Channel.MostAbsentEmployeesAsync();
        }
        
        public System.Data.DataTable AllKeys() {
            return base.Channel.AllKeys();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllKeysAsync() {
            return base.Channel.AllKeysAsync();
        }
        
        public System.Data.DataTable AllIndexes() {
            return base.Channel.AllIndexes();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllIndexesAsync() {
            return base.Channel.AllIndexesAsync();
        }
        
        public System.Data.DataTable AllTableConstrains() {
            return base.Channel.AllTableConstrains();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllTableConstrainsAsync() {
            return base.Channel.AllTableConstrainsAsync();
        }
        
        public System.Data.DataTable AllTablesInDatabaseSolOne() {
            return base.Channel.AllTablesInDatabaseSolOne();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllTablesInDatabaseSolOneAsync() {
            return base.Channel.AllTablesInDatabaseSolOneAsync();
        }
        
        public System.Data.DataTable AllTablesInDatabaseSolTwo() {
            return base.Channel.AllTablesInDatabaseSolTwo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllTablesInDatabaseSolTwoAsync() {
            return base.Channel.AllTablesInDatabaseSolTwoAsync();
        }
        
        public System.Data.DataTable AllColEmpTableSolOne() {
            return base.Channel.AllColEmpTableSolOne();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllColEmpTableSolOneAsync() {
            return base.Channel.AllColEmpTableSolOneAsync();
        }
        
        public System.Data.DataTable AllColEmpTableSolTwo() {
            return base.Channel.AllColEmpTableSolTwo();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> AllColEmpTableSolTwoAsync() {
            return base.Channel.AllColEmpTableSolTwoAsync();
        }
        
        public string ShowFile(string fileName) {
            return base.Channel.ShowFile(fileName);
        }
        
        public System.Threading.Tasks.Task<string> ShowFileAsync(string fileName) {
            return base.Channel.ShowFileAsync(fileName);
        }
    }
}
