//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramKonstruktion.ERP12Reference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Employee", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Employee : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string JobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SsnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string No {
            get {
                return this.NoField;
            }
            set {
                if ((object.ReferenceEquals(this.NoField, value) != true)) {
                    this.NoField = value;
                    this.RaisePropertyChanged("No");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string JobTitle {
            get {
                return this.JobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.JobTitleField, value) != true)) {
                    this.JobTitleField = value;
                    this.RaisePropertyChanged("JobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Ssn {
            get {
                return this.SsnField;
            }
            set {
                if ((object.ReferenceEquals(this.SsnField, value) != true)) {
                    this.SsnField = value;
                    this.RaisePropertyChanged("Ssn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ERP12Reference.ERP1WebServiceSoap")]
    public interface ERP1WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        ProgramKonstruktion.ERP12Reference.CreateEmployeeResponse CreateEmployee(ProgramKonstruktion.ERP12Reference.CreateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.CreateEmployeeResponse> CreateEmployeeAsync(ProgramKonstruktion.ERP12Reference.CreateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        ProgramKonstruktion.ERP12Reference.FindEmployeeResponse FindEmployee(ProgramKonstruktion.ERP12Reference.FindEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.FindEmployeeResponse> FindEmployeeAsync(ProgramKonstruktion.ERP12Reference.FindEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        ProgramKonstruktion.ERP12Reference.UpdateEmployeeResponse UpdateEmployee(ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.UpdateEmployeeResponse> UpdateEmployeeAsync(ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequest request);
        
        // CODEGEN: Generating message contract since element name no from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        ProgramKonstruktion.ERP12Reference.DeleteEmployeeResponse DeleteEmployee(ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.DeleteEmployeeResponse> DeleteEmployeeAsync(ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ERP12Reference.CreateEmployeeRequestBody Body;
        
        public CreateEmployeeRequest() {
        }
        
        public CreateEmployeeRequest(ProgramKonstruktion.ERP12Reference.CreateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string FirstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string ssn;
        
        public CreateEmployeeRequestBody() {
        }
        
        public CreateEmployeeRequestBody(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            this.no = no;
            this.FirstName = FirstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
            this.address = address;
            this.phoneNumber = phoneNumber;
            this.email = email;
            this.ssn = ssn;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ERP12Reference.CreateEmployeeResponseBody Body;
        
        public CreateEmployeeResponse() {
        }
        
        public CreateEmployeeResponse(ProgramKonstruktion.ERP12Reference.CreateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProgramKonstruktion.ERP12Reference.Employee CreateEmployeeResult;
        
        public CreateEmployeeResponseBody() {
        }
        
        public CreateEmployeeResponseBody(ProgramKonstruktion.ERP12Reference.Employee CreateEmployeeResult) {
            this.CreateEmployeeResult = CreateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ERP12Reference.FindEmployeeRequestBody Body;
        
        public FindEmployeeRequest() {
        }
        
        public FindEmployeeRequest(ProgramKonstruktion.ERP12Reference.FindEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        public FindEmployeeRequestBody() {
        }
        
        public FindEmployeeRequestBody(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ERP12Reference.FindEmployeeResponseBody Body;
        
        public FindEmployeeResponse() {
        }
        
        public FindEmployeeResponse(ProgramKonstruktion.ERP12Reference.FindEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProgramKonstruktion.ERP12Reference.Employee FindEmployeeResult;
        
        public FindEmployeeResponseBody() {
        }
        
        public FindEmployeeResponseBody(ProgramKonstruktion.ERP12Reference.Employee FindEmployeeResult) {
            this.FindEmployeeResult = FindEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequestBody Body;
        
        public UpdateEmployeeRequest() {
        }
        
        public UpdateEmployeeRequest(ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string firstName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string lastName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string jobTitle;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string address;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string email;
        
        public UpdateEmployeeRequestBody() {
        }
        
        public UpdateEmployeeRequestBody(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email) {
            this.no = no;
            this.firstName = firstName;
            this.lastName = lastName;
            this.jobTitle = jobTitle;
            this.address = address;
            this.phoneNumber = phoneNumber;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ERP12Reference.UpdateEmployeeResponseBody Body;
        
        public UpdateEmployeeResponse() {
        }
        
        public UpdateEmployeeResponse(ProgramKonstruktion.ERP12Reference.UpdateEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ProgramKonstruktion.ERP12Reference.Employee UpdateEmployeeResult;
        
        public UpdateEmployeeResponseBody() {
        }
        
        public UpdateEmployeeResponseBody(ProgramKonstruktion.ERP12Reference.Employee UpdateEmployeeResult) {
            this.UpdateEmployeeResult = UpdateEmployeeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployee", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequestBody Body;
        
        public DeleteEmployeeRequest() {
        }
        
        public DeleteEmployeeRequest(ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEmployeeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string no;
        
        public DeleteEmployeeRequestBody() {
        }
        
        public DeleteEmployeeRequestBody(string no) {
            this.no = no;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteEmployeeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteEmployeeResponse", Namespace="http://tempuri.org/", Order=0)]
        public ProgramKonstruktion.ERP12Reference.DeleteEmployeeResponseBody Body;
        
        public DeleteEmployeeResponse() {
        }
        
        public DeleteEmployeeResponse(ProgramKonstruktion.ERP12Reference.DeleteEmployeeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteEmployeeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteEmployeeResult;
        
        public DeleteEmployeeResponseBody() {
        }
        
        public DeleteEmployeeResponseBody(bool DeleteEmployeeResult) {
            this.DeleteEmployeeResult = DeleteEmployeeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ERP1WebServiceSoapChannel : ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ERP1WebServiceSoapClient : System.ServiceModel.ClientBase<ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap>, ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap {
        
        public ERP1WebServiceSoapClient() {
        }
        
        public ERP1WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ERP1WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERP1WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ERP1WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramKonstruktion.ERP12Reference.CreateEmployeeResponse ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap.CreateEmployee(ProgramKonstruktion.ERP12Reference.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployee(request);
        }
        
        public ProgramKonstruktion.ERP12Reference.Employee CreateEmployee(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            ProgramKonstruktion.ERP12Reference.CreateEmployeeRequest inValue = new ProgramKonstruktion.ERP12Reference.CreateEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ERP12Reference.CreateEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.FirstName = FirstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            inValue.Body.ssn = ssn;
            ProgramKonstruktion.ERP12Reference.CreateEmployeeResponse retVal = ((ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap)(this)).CreateEmployee(inValue);
            return retVal.Body.CreateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.CreateEmployeeResponse> ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap.CreateEmployeeAsync(ProgramKonstruktion.ERP12Reference.CreateEmployeeRequest request) {
            return base.Channel.CreateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.CreateEmployeeResponse> CreateEmployeeAsync(string no, string FirstName, string lastName, string jobTitle, string address, string phoneNumber, string email, string ssn) {
            ProgramKonstruktion.ERP12Reference.CreateEmployeeRequest inValue = new ProgramKonstruktion.ERP12Reference.CreateEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ERP12Reference.CreateEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.FirstName = FirstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            inValue.Body.ssn = ssn;
            return ((ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap)(this)).CreateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramKonstruktion.ERP12Reference.FindEmployeeResponse ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap.FindEmployee(ProgramKonstruktion.ERP12Reference.FindEmployeeRequest request) {
            return base.Channel.FindEmployee(request);
        }
        
        public ProgramKonstruktion.ERP12Reference.Employee FindEmployee(string no) {
            ProgramKonstruktion.ERP12Reference.FindEmployeeRequest inValue = new ProgramKonstruktion.ERP12Reference.FindEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ERP12Reference.FindEmployeeRequestBody();
            inValue.Body.no = no;
            ProgramKonstruktion.ERP12Reference.FindEmployeeResponse retVal = ((ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap)(this)).FindEmployee(inValue);
            return retVal.Body.FindEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.FindEmployeeResponse> ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap.FindEmployeeAsync(ProgramKonstruktion.ERP12Reference.FindEmployeeRequest request) {
            return base.Channel.FindEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.FindEmployeeResponse> FindEmployeeAsync(string no) {
            ProgramKonstruktion.ERP12Reference.FindEmployeeRequest inValue = new ProgramKonstruktion.ERP12Reference.FindEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ERP12Reference.FindEmployeeRequestBody();
            inValue.Body.no = no;
            return ((ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap)(this)).FindEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramKonstruktion.ERP12Reference.UpdateEmployeeResponse ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap.UpdateEmployee(ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployee(request);
        }
        
        public ProgramKonstruktion.ERP12Reference.Employee UpdateEmployee(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email) {
            ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequest inValue = new ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            ProgramKonstruktion.ERP12Reference.UpdateEmployeeResponse retVal = ((ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap)(this)).UpdateEmployee(inValue);
            return retVal.Body.UpdateEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.UpdateEmployeeResponse> ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap.UpdateEmployeeAsync(ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequest request) {
            return base.Channel.UpdateEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.UpdateEmployeeResponse> UpdateEmployeeAsync(string no, string firstName, string lastName, string jobTitle, string address, string phoneNumber, string email) {
            ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequest inValue = new ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ERP12Reference.UpdateEmployeeRequestBody();
            inValue.Body.no = no;
            inValue.Body.firstName = firstName;
            inValue.Body.lastName = lastName;
            inValue.Body.jobTitle = jobTitle;
            inValue.Body.address = address;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.email = email;
            return ((ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap)(this)).UpdateEmployeeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ProgramKonstruktion.ERP12Reference.DeleteEmployeeResponse ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap.DeleteEmployee(ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployee(request);
        }
        
        public bool DeleteEmployee(string no) {
            ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequest inValue = new ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequestBody();
            inValue.Body.no = no;
            ProgramKonstruktion.ERP12Reference.DeleteEmployeeResponse retVal = ((ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap)(this)).DeleteEmployee(inValue);
            return retVal.Body.DeleteEmployeeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.DeleteEmployeeResponse> ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap.DeleteEmployeeAsync(ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequest request) {
            return base.Channel.DeleteEmployeeAsync(request);
        }
        
        public System.Threading.Tasks.Task<ProgramKonstruktion.ERP12Reference.DeleteEmployeeResponse> DeleteEmployeeAsync(string no) {
            ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequest inValue = new ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequest();
            inValue.Body = new ProgramKonstruktion.ERP12Reference.DeleteEmployeeRequestBody();
            inValue.Body.no = no;
            return ((ProgramKonstruktion.ERP12Reference.ERP1WebServiceSoap)(this)).DeleteEmployeeAsync(inValue);
        }
    }
}
