//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProgramKonstruktion.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SYST4DEV01;Initial Catalog=StoreIT2;Persist Security Info=True;User I" +
            "D=tgang;Password=tgang1")]
        public string StoreIT2ConnectionString {
            get {
                return ((string)(this["StoreIT2ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SYST4DEV01;Initial Catalog=StoreIT3;User ID=tgang;Password=tgang1")]
        public string StoreIT3ConnectionString {
            get {
                return ((string)(this["StoreIT3ConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=SYST4DEV01;Initial Catalog=STOREITNEW;Persist Security Info=True;User" +
            " ID=tgang;Password=tgang1")]
        public string STOREITNEWConnectionString {
            get {
                return ((string)(this["STOREITNEWConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/WebApplication/WebServiceAssignment.asmx")]
        public string ProgramKonstruktion_OpenFileService_WebServiceAssignment {
            get {
                return ((string)(this["ProgramKonstruktion_OpenFileService_WebServiceAssignment"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/SqlWebApplication/SqlWebService.asmx")]
        public string ProgramKonstruktion_SqlWebReference_SqlWebService {
            get {
                return ((string)(this["ProgramKonstruktion_SqlWebReference_SqlWebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ERP1WebApplication/ERP1WebService.asmx")]
        public string ProgramKonstruktion_ERP1WebRef_ERP1WebService {
            get {
                return ((string)(this["ProgramKonstruktion_ERP1WebRef_ERP1WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/WebAppERP/WebServiceERP12.asmx")]
        public string ProgramKonstruktion_NewWebRefMeta_WebServiceERP12 {
            get {
                return ((string)(this["ProgramKonstruktion_NewWebRefMeta_WebServiceERP12"]));
            }
        }
    }
}
